package io.github.dzkchen.dhen.gui

internal const val FEATURES_TAB = 0
internal const val MARGIN = 8
internal const val COLUMN_WIDTH = 118
internal const val COLUMN_GAP = 8
internal const val COLUMN_RADIUS = 6f
internal const val HEADER_HEIGHT = 18
internal const val HEADER_RULE_INSET = 4
internal const val BODY_PAD = 6
internal const val ROW_HEIGHT = 13
internal const val ROW_RAIL_WIDTH = 2
internal const val FOCUS_RADIUS = 3f
internal const val CHEVRON_HIT_SLOP = 4
internal const val SCROLLBAR_WIDTH = 2
internal const val SCROLLBAR_INSET = 3
internal const val SCROLLBAR_MIN_THUMB = 12
internal const val TOOLTIP_PAD = 5
internal const val TOOLTIP_GAP = 6
internal const val TOOLTIP_RADIUS = 4f
internal const val NO_POINTER = Int.MIN_VALUE
internal const val SETTINGS_PAD = 3
internal const val CONTENT_PAD = 6
internal const val CONTROLS_WIDTH = COLUMN_WIDTH - 2 * CONTENT_PAD
internal const val TAB_TOP = 6
internal const val BAR_HEIGHT = 22
internal const val BAR_PAD = 3
internal const val TAB_PAD = 10
internal const val TAB_GAP = 2
internal const val CHROME_BOTTOM = TAB_TOP + BAR_HEIGHT
internal const val SEARCH_TOP = CHROME_BOTTOM + 8
internal const val SEARCH_WIDTH = 240
internal const val SEARCH_HEIGHT = 22
internal const val SEARCH_PAD = 10
internal const val SEARCH_MAX_LENGTH = 20
internal const val FIELD_TOP = SEARCH_TOP + SEARCH_HEIGHT + 12
internal const val SCROLL_STEP = 24
internal const val PANEL_WIDTH = SEARCH_WIDTH
internal const val PANEL_CONTROLS_WIDTH = PANEL_WIDTH - 2 * CONTENT_PAD
internal const val SECTION_GAP = 6
internal const val SECTION_PAD = 4
internal const val EMPTY_SECTION_HEIGHT = ROW_HEIGHT
internal const val SEARCH_PLACEHOLDER = "Search"
internal const val NO_MATCH_LABEL = "No matches"
internal const val EMPTY_SECTION_LABEL = "Nothing here yet"
internal const val EXPAND_GLYPH = "+"
internal const val COLLAPSE_GLYPH = "-"
internal const val CHEVRON_COLLAPSED = "›"
internal const val CHEVRON_EXPANDED = "⌄"
internal val TAB_LABELS = arrayOf("Features", "Settings")

internal fun fieldBottomOf(viewportHeight: Int): Int = viewportHeight - MARGIN
